datasets:
  zone_monthly_3_02:
    name: electricity_generation_3_02
    description: "3-02 發電量"
    url: "https://ea01.moeaea.gov.tw/a0303/02/api/v1/zone/monthly/3/2"
    output_dir: "output/zone_monthly_3_02"
    raw_dir: "data/raw/zone_monthly_3_02"
    excel_file: "electricity_generation_3_02.xlsx"
    dataset_type: "electricity_generation"
    value_unit: "GWh"

  zone_monthly_3_03:
    name: installed_capacity_3_03
    description: "3-03 發電裝置容量"
    url: "https://ea01.moeaea.gov.tw/a0303/02/api/v1/zone/monthly/3/3/"
    output_dir: "output/zone_monthly_3_03"
    raw_dir: "data/raw/zone_monthly_3_03"
    excel_file: "installed_capacity_3_03.xlsx"
    dataset_type: "installed_capacity"
    value_unit: "MW"

  zone_monthly_4_01:
    name: renewable_electricity_generation_4_01
    description: "4-01 再生能源發電量"
    url: "https://ea01.moeaea.gov.tw/a0303/02/api/v1/zone/monthly/4/1"
    output_dir: "output/zone_monthly_4_01"
    raw_dir: "data/raw/zone_monthly_4_01"
    excel_file: "renewable_electricity_generation_4_01.xlsx"
    dataset_type: "renewable_electricity_generation"
    value_unit: "MWh"

  zone_monthly_4_02:
    name: renewable_installed_capacity_4_02
    description: "4-02 再生能源裝(設)置容量"
    url: "https://ea01.moeaea.gov.tw/a0303/02/api/v1/zone/monthly/4/2"
    output_dir: "output/zone_monthly_4_02"
    raw_dir: "data/raw/zone_monthly_4_02"
    excel_file: "renewable_installed_capacity_4_02.xlsx"
    dataset_type: "renewable_installed_capacity"
    value_unit: "MW"

  zone_monthly_4_03:
    name: renewable_enterprise_sales_4_03
    description: "4-03 再生能源發電業直轉供及躉售"
    url: "https://ea01.moeaea.gov.tw/a0303/02/api/v1/zone/monthly/4/3/"
    output_dir: "output/zone_monthly_4_03"
    raw_dir: "data/raw/zone_monthly_4_03"
    excel_file: "renewable_enterprise_sales_4_03.xlsx"
    dataset_type: "renewable_enterprise_sales"
    value_unit: "MWh"
